Linux Build: Use Eina_Lock instead of pthread_mutex_t (#112)
`_eina_tracking_lock` was been seted as diferents types at `eina_main.c`
and `eina_inline_lock_posix.x` causing:
```
   ../src/lib/eina/eina_main.c:113:20: error: conflicting types for '_eina_tracking_lock'
     113 | EINA_API Eina_Lock _eina_tracking_lock;
         |                    ^~~~~~~~~~~~~~~~~~~
   In file included from ../src/lib/eina/eina_lock.h:103,
                    from ../src/lib/eina/eina_main.c:43:
   ../src/lib/eina/eina_inline_lock_posix.x:155:33: note: previous declaration of '_eina_tracking_lock' was here
     155 | EINA_API extern pthread_mutex_t _eina_tracking_lock;
         |                                 ^~~~~~~~~~~~~~~~~~~
```