Add LIB_API.h to files to be installed
Travis-CI [yields](https://travis-ci.com/github/expertisesolutions/efl/builds/174232232#L5012):
```
/usr/local/include/eo-1/Eo.h:7:10: fatal error: eo_api.h: No such file or directory
    7 | #include <eo_api.h>
      |          ^~~~~~~~~~
```
Because `eo_api.h` wasn't defined as a header to be installed.

This PR sets every `LIB_api.h` as a header to be installed.

`Ector` is not installed, so its API header doesn't need it either.