Remove unnecessary additional argument
`eina_lock_take` was reciving an aditional `NULL` argumment causing:
```
  ../src/lib/eina/eina_main.c:322:4: error: too many arguments to function 'eina_lock_take'
    322 |    eina_lock_take(&_eina_tracking_lock, NULL);
        |    ^~~~~~~~~~~~~~
  In file included from ../src/lib/eina/eina_main.c:43:
  ../src/lib/eina/eina_lock.h:169:27: note: declared here
    169 | EINA_API Eina_Lock_Result eina_lock_take(Eina_Lock *mutex);
        |                           ^~~~~~~~~~~~~~

```