Guard ole2.h with WIN32_LEAN_AND_MEAN
Indirectly `ole2.h` seems to be including `winsock.h` causing some
errors like:
```
In file included from ../src/lib/ecore_win32/ecore_win32_dnd_enumformatetc.cpp:4:
In file included from ..\src\lib\ecore_win32/ecore_win32_dnd_enumformatetc.h:4:
In file included from ..\src\lib\evil/evil_private.h:52:
In file included from ..\src\lib\evil/evil_time.h:9:
In file included from C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winsock2.h:116:
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared\ws2def.h(240,16): error: redefinition of 'sockaddr'
typedef struct sockaddr {
               ^
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winsock.h(482,8): note: previous definition is here
struct sockaddr {
       ^
In file included from ../src/lib/ecore_win32/ecore_win32_dnd_enumformatetc.cpp:4:
In file included from ..\src\lib\ecore_win32/ecore_win32_dnd_enumformatetc.h:4:
In file included from ..\src\lib\evil/evil_private.h:52:
In file included from ..\src\lib\evil/evil_time.h:9:
In file included from C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winsock2.h:116:
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared\ws2def.h(442,5): error: expected identifier
    IPPROTO_ICMP          = 1,
    ^
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winsock.h(211,33): note: expanded from macro 'IPPROTO_ICMP'
```

Which are know to be `winsock.h` vs `winsock2.h` related.

By guarding it with `WIN32_LEAN_AND_MEAN` we prevent this indirect
include of `winsock.h`